import type { LucideIcon } from 'lucide-react'
import {
  ActivityIcon,
  AlertCircleIcon,
  AlertTriangleIcon,
  ArchiveIcon,
  ArrowDownUpIcon,
  ArrowRightIcon,
  AtSignIcon,
  AwardIcon,
  BarChart3Icon,
  BellIcon,
  BookmarkIcon,
  BotIcon,
  BoxIcon,
  BriefcaseBusinessIcon,
  Building2Icon,
  CalendarDaysIcon,
  CalendarIcon,
  CheckIcon,
  ChevronDownIcon,
  ChevronRightIcon,
  CircleDotIcon,
  CircleHelpIcon,
  ClipboardCopyIcon,
  ClipboardListIcon,
  ClockIcon,
  CloudIcon,
  DatabaseIcon,
  DownloadIcon,
  EyeIcon,
  FileBarChartIcon,
  FileTextIcon,
  FilterIcon,
  FlameIcon,
  FolderOpenIcon,
  GaugeIcon,
  GavelIcon,
  GlobeIcon,
  HashIcon,
  HistoryIcon,
  HomeIcon,
  ImageIcon,
  InboxIcon,
  InfoIcon,
  KeyRoundIcon,
  LayersIcon,
  LayoutDashboardIcon,
  Link2Icon,
  ListChecksIcon,
  ListOrderedIcon,
  LockIcon,
  MailIcon,
  MapPinIcon,
  MessageSquareIcon,
  MoonIcon,
  PackageIcon,
  PaperclipIcon,
  PencilLineIcon,
  PhoneCallIcon,
  PhoneIcon,
  PinIcon,
  PlugIcon,
  PlusIcon,
  RefreshCwIcon,
  ScaleIcon,
  SearchIcon,
  SettingsIcon,
  Share2Icon,
  ShieldAlertIcon,
  ShieldCheckIcon,
  ShieldIcon,
  SlidersHorizontalIcon,
  SparklesIcon,
  SunIcon,
  TablePropertiesIcon,
  TagIcon,
  TagsIcon,
  TargetIcon,
  TextAlignStartIcon,
  ToggleLeftIcon,
  Trash2Icon,
  TrendingUpIcon,
  UploadIcon,
  UserIcon,
  UserPlusIcon,
  UsersIcon,
  WrenchIcon,
  XIcon,
} from 'lucide-react'

/**
 * Catálogo de ícones do sistema — chaves estáveis para grids em popover, configuração de campo, etc.
 * Importe `APP_ICONS`, `getAppIcon` ou `APP_ICON_OPTIONS` conforme o caso.
 */
export const APP_ICONS = {
  activity: ActivityIcon,
  alertCircle: AlertCircleIcon,
  alertTriangle: AlertTriangleIcon,
  archive: ArchiveIcon,
  arrowDownUp: ArrowDownUpIcon,
  arrowRight: ArrowRightIcon,
  atSign: AtSignIcon,
  award: AwardIcon,
  barChart3: BarChart3Icon,
  bell: BellIcon,
  bookmark: BookmarkIcon,
  bot: BotIcon,
  box: BoxIcon,
  briefcase: BriefcaseBusinessIcon,
  building2: Building2Icon,
  calendar: CalendarIcon,
  calendarDays: CalendarDaysIcon,
  check: CheckIcon,
  chevronDown: ChevronDownIcon,
  chevronRight: ChevronRightIcon,
  circleDot: CircleDotIcon,
  circleHelp: CircleHelpIcon,
  clipboardCopy: ClipboardCopyIcon,
  clipboardList: ClipboardListIcon,
  clock: ClockIcon,
  cloud: CloudIcon,
  database: DatabaseIcon,
  download: DownloadIcon,
  eye: EyeIcon,
  fileBarChart: FileBarChartIcon,
  fileText: FileTextIcon,
  filter: FilterIcon,
  flame: FlameIcon,
  folderOpen: FolderOpenIcon,
  gauge: GaugeIcon,
  gavel: GavelIcon,
  globe: GlobeIcon,
  hash: HashIcon,
  history: HistoryIcon,
  home: HomeIcon,
  image: ImageIcon,
  inbox: InboxIcon,
  info: InfoIcon,
  keyRound: KeyRoundIcon,
  layers: LayersIcon,
  layoutDashboard: LayoutDashboardIcon,
  link2: Link2Icon,
  listChecks: ListChecksIcon,
  listOrdered: ListOrderedIcon,
  lock: LockIcon,
  mail: MailIcon,
  mapPin: MapPinIcon,
  messageSquare: MessageSquareIcon,
  moon: MoonIcon,
  package: PackageIcon,
  paperclip: PaperclipIcon,
  pencilLine: PencilLineIcon,
  phone: PhoneIcon,
  phoneCall: PhoneCallIcon,
  pin: PinIcon,
  plug: PlugIcon,
  plus: PlusIcon,
  refreshCw: RefreshCwIcon,
  scale: ScaleIcon,
  search: SearchIcon,
  settings: SettingsIcon,
  share2: Share2Icon,
  shield: ShieldIcon,
  shieldAlert: ShieldAlertIcon,
  shieldCheck: ShieldCheckIcon,
  slidersHorizontal: SlidersHorizontalIcon,
  sparkles: SparklesIcon,
  sun: SunIcon,
  tableProperties: TablePropertiesIcon,
  tag: TagIcon,
  tags: TagsIcon,
  target: TargetIcon,
  textAlignStart: TextAlignStartIcon,
  toggleLeft: ToggleLeftIcon,
  trash2: Trash2Icon,
  trendingUp: TrendingUpIcon,
  upload: UploadIcon,
  user: UserIcon,
  userPlus: UserPlusIcon,
  users: UsersIcon,
  wrench: WrenchIcon,
  x: XIcon,
} as const satisfies Record<string, LucideIcon>

export type AppIconId = keyof typeof APP_ICONS

export const APP_ICON_IDS = Object.keys(APP_ICONS) as AppIconId[]

export function getAppIcon(id: AppIconId): LucideIcon {
  return APP_ICONS[id]
}

export function isAppIconId(value: string): value is AppIconId {
  return value in APP_ICONS
}

/** Opção para grid de seleção em popover (ícone + rótulo curto). */
export type AppIconOption = Readonly<{
  id: AppIconId
  label: string
  /** Agrupa em seções na UI, ex.: "Navegação", "Ações". */
  group?: string
}>

/** Lista pronta para picker — personalize rótulos conforme a tela ou derive de `APP_ICON_IDS`. */
export const APP_ICON_OPTIONS: readonly AppIconOption[] = [
  { id: 'layoutDashboard', label: 'Painel', group: 'Navegação' },
  { id: 'inbox', label: 'Caixa / denúncias', group: 'Navegação' },
  { id: 'barChart3', label: 'Indicadores', group: 'Navegação' },
  { id: 'fileText', label: 'Relatórios', group: 'Navegação' },
  { id: 'database', label: 'Dados mestres', group: 'Navegação' },
  { id: 'settings', label: 'Configurações', group: 'Navegação' },
  { id: 'circleHelp', label: 'Ajuda', group: 'Navegação' },
  { id: 'shieldAlert', label: 'Alerta / denúncia', group: 'Segurança' },
  { id: 'shield', label: 'Proteção', group: 'Segurança' },
  { id: 'shieldCheck', label: 'Verificado', group: 'Segurança' },
  { id: 'lock', label: 'Bloqueio', group: 'Segurança' },
  { id: 'keyRound', label: 'Chave / senha', group: 'Segurança' },
  { id: 'user', label: 'Usuário', group: 'Pessoas' },
  { id: 'users', label: 'Equipe', group: 'Pessoas' },
  { id: 'userPlus', label: 'Convite', group: 'Pessoas' },
  { id: 'calendar', label: 'Calendário', group: 'Tempo' },
  { id: 'calendarDays', label: 'Datas', group: 'Tempo' },
  { id: 'clock', label: 'Relógio / prazo', group: 'Tempo' },
  { id: 'history', label: 'Histórico', group: 'Tempo' },
  { id: 'mail', label: 'E-mail', group: 'Comunicação' },
  { id: 'phone', label: 'Telefone', group: 'Comunicação' },
  { id: 'phoneCall', label: 'Ligação', group: 'Comunicação' },
  { id: 'messageSquare', label: 'Mensagem', group: 'Comunicação' },
  { id: 'globe', label: 'Web / canal', group: 'Comunicação' },
  { id: 'building2', label: 'Organização', group: 'Local' },
  { id: 'mapPin', label: 'Localização', group: 'Local' },
  { id: 'hash', label: 'Código', group: 'Conteúdo' },
  { id: 'tags', label: 'Categorias', group: 'Conteúdo' },
  { id: 'tag', label: 'Tag', group: 'Conteúdo' },
  { id: 'textAlignStart', label: 'Descrição', group: 'Conteúdo' },
  { id: 'listOrdered', label: 'Ordem', group: 'Conteúdo' },
  { id: 'circleDot', label: 'Status', group: 'Conteúdo' },
  { id: 'toggleLeft', label: 'Ativo / inativo', group: 'Conteúdo' },
  { id: 'clipboardList', label: 'Lista / SLA', group: 'Conteúdo' },
  { id: 'gauge', label: 'Prioridade', group: 'Conteúdo' },
  { id: 'briefcase', label: 'Departamento', group: 'Conteúdo' },
  { id: 'plug', label: 'Integração / entrada', group: 'Conteúdo' },
  { id: 'plus', label: 'Novo', group: 'Ações' },
  { id: 'pencilLine', label: 'Editar', group: 'Ações' },
  { id: 'eye', label: 'Visualizar', group: 'Ações' },
  { id: 'download', label: 'Exportar / baixar', group: 'Ações' },
  { id: 'upload', label: 'Enviar arquivo', group: 'Ações' },
  { id: 'share2', label: 'Compartilhar', group: 'Ações' },
  { id: 'clipboardCopy', label: 'Copiar', group: 'Ações' },
  { id: 'archive', label: 'Arquivar', group: 'Ações' },
  { id: 'trash2', label: 'Excluir', group: 'Ações' },
  { id: 'search', label: 'Buscar', group: 'Ações' },
  { id: 'filter', label: 'Filtrar', group: 'Ações' },
  { id: 'slidersHorizontal', label: 'Filtros avançados', group: 'Ações' },
  { id: 'refreshCw', label: 'Atualizar', group: 'Ações' },
  { id: 'x', label: 'Fechar / limpar', group: 'Ações' },
  { id: 'check', label: 'Confirmar', group: 'Ações' },
  { id: 'sparkles', label: 'Destaque / Pro', group: 'Outros' },
  { id: 'bot', label: 'IA / copiloto', group: 'Outros' },
  { id: 'bell', label: 'Notificação', group: 'Outros' },
  { id: 'activity', label: 'Atividade', group: 'Outros' },
  { id: 'target', label: 'Meta', group: 'Outros' },
  { id: 'award', label: 'Reconhecimento', group: 'Outros' },
  { id: 'scale', label: 'Compliance / legal', group: 'Outros' },
  { id: 'gavel', label: 'Julgamento / decisão', group: 'Outros' },
  { id: 'wrench', label: 'Ferramentas', group: 'Outros' },
  { id: 'package', label: 'Pacote / entrega', group: 'Outros' },
  { id: 'paperclip', label: 'Anexo', group: 'Outros' },
  { id: 'image', label: 'Imagem', group: 'Outros' },
  { id: 'link2', label: 'Link', group: 'Outros' },
  { id: 'pin', label: 'Fixar', group: 'Outros' },
  { id: 'bookmark', label: 'Marcador', group: 'Outros' },
  { id: 'folderOpen', label: 'Pasta', group: 'Outros' },
  { id: 'layers', label: 'Camadas', group: 'Outros' },
  { id: 'tableProperties', label: 'Tabela / visão', group: 'Outros' },
  { id: 'listChecks', label: 'Checklist', group: 'Outros' },
  { id: 'fileBarChart', label: 'Relatório analítico', group: 'Outros' },
  { id: 'trendingUp', label: 'Evolução', group: 'Outros' },
  { id: 'flame', label: 'Urgência', group: 'Outros' },
  { id: 'cloud', label: 'Nuvem', group: 'Outros' },
  { id: 'box', label: 'Caixa / estoque', group: 'Outros' },
  { id: 'home', label: 'Início', group: 'Navegação' },
  { id: 'moon', label: 'Modo escuro', group: 'UI' },
  { id: 'sun', label: 'Modo claro', group: 'UI' },
  { id: 'info', label: 'Informação', group: 'UI' },
  { id: 'alertCircle', label: 'Aviso', group: 'UI' },
  { id: 'alertTriangle', label: 'Atenção', group: 'UI' },
] as const

/** Agrupa opções para seções em popover. */
export function groupAppIconOptions(
  options: readonly AppIconOption[] = APP_ICON_OPTIONS,
): Record<string, AppIconOption[]> {
  const out: Record<string, AppIconOption[]> = {}
  for (const opt of options) {
    const g = opt.group ?? 'Outros'
    ;(out[g] ??= []).push(opt)
  }
  return out
}
